language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn build-editor
  - npm install codecov -g
after_success:
  - codecov
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $github_token
    local-dir: build
    on:
      branch: master
keep-history: true